import type { Opportunity } from "./grants";

// Generated from the verified community-aligned opportunity research (2026).
// 43 programs surfaced across 6 lanes; regenerate when cycles refresh.
export const OPPORTUNITIES: Opportunity[] = [
  {
    "id": "acre3-advancing-colorado-s-renewable-ene",
    "name": "ACRE3 - Advancing Colorado's Renewable Energy & Energy Efficiency",
    "funder": "Colorado Department of Agriculture (Agricultural Value-Added Development Board)",
    "awardRange": "Not published as a fixed range on the page; varies by project (implementation vs. audit/report)",
    "funds": "Two FY2026 tracks: (1) Implementation Grants for construction/installation of energy efficiency and renewable energy projects on farms and ranches; (2) Energy Audits & Technical Reports/Assessments funded for producers planning energy projects. Technologies: solar hot water, agrivoltaics, agricultural hydropower, energy efficiency, and all clean-energy types.",
    "fit": "Strong fit. Aligns with Paonia's organic-ag base and its just-transition story as a former coal region moving toward clean energy. Local farms, ranches, and ag processors (orchards, wineries) are direct applicants for on-site solar, efficiency, or agrivoltaics.",
    "eligibleApplicant": "business-or-resident",
    "cycle": "Annual funding opportunities",
    "nextDeadline": "Implementation Grants: open now through May 29, 2026",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://ag.colorado.gov/conservation/acre3-energy-grants",
    "category": "agriculture"
  },
  {
    "id": "agricultural-workforce-development-progr",
    "name": "Agricultural Workforce Development Program (AWDP) - Internship Reimbursement",
    "funder": "Colorado Department of Agriculture",
    "awardRange": "Up to $5,000 per intern (max 3 interns/year); reimburses up to 50% of intern employment cost",
    "funds": "Reimburses Colorado farms, ranches, and ag businesses up to 50% of the actual cost to employ an intern, up to $5,000 per intern (plus up to 10% fixed overhead). Up to 3 internships per business per year. 75%+ of reimbursement must go to the intern.",
    "fit": "Strong fit. North Fork farms, ranches, orchards, and wineries that train the next generation of farmers are exactly who this serves. Directly supports Paonia's young-farmer pipeline and ag identity.",
    "eligibleApplicant": "business-or-resident",
    "cycle": "Annual (application window each October)",
    "nextDeadline": "Between cycles now",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://ag.colorado.gov/markets/agricultural-workforce-development-program",
    "category": "agriculture"
  },
  {
    "id": "community-food-access-program-refundable",
    "name": "Community Food Access Program - Refundable Tax Credits",
    "funder": "Colorado Department of Agriculture",
    "awardRange": "Refundable tax credit amount varies by qualifying equipment/distribution costs",
    "funds": "Refundable state tax credits for small food retailers and small Colorado-owned/operated family farms that make costly equipment purchases or incur delivery/distribution fees to increase access to healthy food in low-income and underserved areas.",
    "fit": "Good fit. Paonia is a small rural town with underserved-area characteristics; local small farms and small grocers/retailers selling healthy food qualify. Directly supports the local-food economy.",
    "eligibleApplicant": "business-or-resident",
    "cycle": "Recurring tri-annual application windows",
    "nextDeadline": "2026 tax-credit application windows close April 30,…",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://ag.colorado.gov/markets/markets-funding/community-food-access-program",
    "category": "agriculture"
  },
  {
    "id": "farmers-market-local-food-promotion-prog",
    "name": "Farmers Market & Local Food Promotion Program (FMPP / LFPP)",
    "funder": "USDA Agricultural Marketing Service (Local Agriculture Market Program / LAMP)",
    "awardRange": "FMPP $50,000-$500,000; LFPP $25,000-$500,000 (by project type); 25% cost share required",
    "funds": "FMPP funds direct producer-to-consumer outlets (farmers markets, CSAs, roadside stands): Capacity Building $50k-$250k, Community Development $100k-$500k, turnkey options $50k-$100k. LFPP funds intermediary local/regional supply chains (aggregation, processing, distribution): Planning $25k-$100k, Implementation $100k-$500k, turnkey $50k-$100k. 25% cost share required.",
    "fit": "Strong fit. Paonia's farmers markets, CSAs, and farm-to-table supply chains are core to its identity. A nonprofit (e.g. Valley Food Partnership, Western Slope Conservation Center), the Town, a food council, or a producer association could apply.",
    "eligibleApplicant": "both",
    "cycle": "Annual (FY cycles)",
    "nextDeadline": "FY26 applications due June 5, 2026",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://www.ams.usda.gov/services/grants/lfpp",
    "category": "agriculture"
  },
  {
    "id": "nextgen-ag-leadership-grant-program",
    "name": "NextGen Ag Leadership Grant Program",
    "funder": "Colorado Department of Agriculture",
    "awardRange": "Up to $25,000 per project (smaller $5,000-$10,000 projects encouraged)",
    "funds": "Grants up to $25,000 (smaller $5k-$10k projects encouraged) to organizations and educational institutions for leadership development of Colorado's emerging food and agriculture leaders.",
    "fit": "Good fit. A Paonia-area nonprofit (e.g. The Learning Council, Valley Food Partnership) or the school district could fund leadership/entrepreneurial training for emerging farmers and food-system workers. Past recipients include Western Slope and Western Colorado organizations.",
    "eligibleApplicant": "both",
    "cycle": "Annual (opens each spring)",
    "nextDeadline": "Closed for 2026",
    "communityTheme": "organic agriculture and local food",
    "confidence": "medium",
    "link": "https://ag.colorado.gov/markets/markets-funding/nextgen-ag-leadership-grant-program",
    "category": "agriculture"
  },
  {
    "id": "rural-business-development-grant-rbdg",
    "name": "Rural Business Development Grant (RBDG)",
    "funder": "USDA Rural Development (Colorado state office)",
    "awardRange": "Opportunity grants limited to <=10% of annual program funds; Enterprise grants vary by project. No fixed per-award cap published; ~$27.7M national pool",
    "funds": "Opportunity and Enterprise grants for technical assistance, training, and small/emerging-business support in rural communities of 50,000 or fewer. ~$27.7 million available nationally for FY2026.",
    "fit": "Good fit. Paonia (pop ~1,500) is comfortably rural-eligible. The Town or a local nonprofit can apply to fund business incubation, ag-business technical assistance, or Main Street economic development that benefits local farms and businesses. Note: individual farms/businesses are beneficiaries, not direct applicants.",
    "eligibleApplicant": "both",
    "cycle": "Annual (FY cycles)",
    "nextDeadline": "FY2026: SECD-priority applications due June 15, 2026…",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants",
    "category": "agriculture"
  },
  {
    "id": "specialty-crop-block-grant-program-scbgp",
    "name": "Specialty Crop Block Grant Program (SCBGP) - Colorado",
    "funder": "USDA AMS via Colorado Department of Agriculture (CDA)",
    "awardRange": "~$700,000 total pool for FFY 2026; individual awards vary by project",
    "funds": "Projects benefiting Colorado specialty crops (fruits, vegetables, tree nuts, nursery crops, etc.) - marketing, research, food safety, pest/disease, market access. ~$700,000 available for FFY 2026.",
    "fit": "Strong fit. The North Fork Valley is Colorado's orchard, vineyard, and farm-to-table heart - specialty crops (tree fruit, wine grapes, vegetables) are its identity. Projects must benefit a broader group, region, or industry segment (not a single farm), so a Western Slope Conservation Center, Valley Food Partnership-style collaborative, or regional grower group is the ideal applicant.",
    "eligibleApplicant": "both",
    "cycle": "Annual (FFY cycles)",
    "nextDeadline": "Phase 1 concept proposals: Jan 5 - Feb 13, 2026",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://ag.colorado.gov/markets/markets-funding/specialty-crop-block-grant-program",
    "category": "agriculture"
  },
  {
    "id": "value-added-producer-grant-vapg",
    "name": "Value-Added Producer Grant (VAPG)",
    "funder": "USDA Rural Development (Rural Business-Cooperative Service)",
    "awardRange": "Up to $50,000 (planning) or $200,000 (working capital) per FY2026 NOFO; 1:1 match required",
    "funds": "Planning grants (capped at $50,000 in FY2026) and working capital grants (capped at $200,000 in FY2026) to help producers process and market value-added products. ~$25 million available nationally. Requires 1:1 non-federal match.",
    "fit": "Strong fit. North Fork producers turning raw crops into value-added products - wine, cider, jam, dried fruit, branded organic produce - are exactly the target. A Paonia orchard, winery, or producer cooperative is a natural applicant.",
    "eligibleApplicant": "business-or-resident",
    "cycle": "Annual (FY cycles, typically opens early in the calendar year)",
    "nextDeadline": "FY2026 window: Feb 17 - Apr 22, 2026",
    "communityTheme": "organic agriculture and local food",
    "confidence": "high",
    "link": "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants",
    "category": "agriculture"
  },
  {
    "id": "arts-in-society-grant",
    "name": "Arts in Society Grant",
    "funder": "RedLine Contemporary Art Center, administering a funder cohort (Bonfils-Stanton Foundation, Colorado Creative Industries, The Colorado Health Foundation, Denver Arts & Venues, Bee Vradenburg Foundation)",
    "awardRange": "$5,000 to $35,000",
    "funds": "Project grants of $5,000-$35,000 for arts projects that engage a social issue through cross-sector work. Does not fund capital/facility projects.",
    "fit": "Open to any Colorado individual artist, nonprofit, school, or government entity with an arts idea addressing a social issue, so Paonia applicants qualify. Good match for arts projects tied to local concerns (just transition from coal, food access, rural mental health). Narrower than general arts funding because it requires a social-issue and cross-sector angle.",
    "eligibleApplicant": "both",
    "cycle": "Annual, LOI typically opens ~July",
    "nextDeadline": "No 2026-27 cycle is posted yet",
    "communityTheme": "arts-culture",
    "confidence": "low",
    "link": "https://www.redlineart.org/ais-apply-for-a-grant",
    "category": "arts-culture"
  },
  {
    "id": "certified-creative-district-project-tech",
    "name": "Certified Creative District Project & Technical Assistance Fund Grant",
    "funder": "Colorado Creative Industries (OEDIT)",
    "awardRange": "Project/TA fund (amount varies, local match required); up to $10,000 cash award for newly certified districts",
    "funds": "Project and technical/professional assistance grant for already-certified Creative Districts to advance strategic goals (local match required). Newly certified districts can also receive a cash award up to $10,000.",
    "fit": "Directly applicable: Paonia is an existing Certified Colorado Creative District (the Paonia Creative District, run by the North Fork Valley Creative Coalition). Districts certified a year or more may apply to the project/TA fund. Highly specific to Paonia's exact situation.",
    "eligibleApplicant": "nonprofit",
    "cycle": "Rolling, by fiscal year (FY26 closed Apr 14, 2026)",
    "nextDeadline": "Rolling",
    "communityTheme": "arts-culture",
    "confidence": "medium",
    "link": "https://oedit.colorado.gov/colorado-creative-districts",
    "category": "arts-culture"
  },
  {
    "id": "colorado-creates-grant",
    "name": "Colorado Creates Grant",
    "funder": "Colorado Creative Industries (OEDIT), supported by the NEA",
    "awardRange": "$6,000 to $14,000 per application (flat, tiered by organization revenue)",
    "funds": "General operating support for arts-focused organizations (flat award tiered by cash operating revenue): $6,000 (revenue $25k-$99,999) up to $14,000 (revenue $1M+).",
    "fit": "Paonia is a state-certified Creative District (the Paonia Creative District, managed by the North Fork Valley Creative Coalition since 2013). Arts-focused local nonprofits such as NFVCC qualify and can use general operating support to sustain galleries, First Fridays, and programming.",
    "eligibleApplicant": "nonprofit",
    "cycle": "Annual (opens Feb, due early May)",
    "nextDeadline": "Annual cycle: applications open early February and c…",
    "communityTheme": "arts-culture",
    "confidence": "medium",
    "link": "https://oedit.colorado.gov/colorado-creates-grant",
    "category": "arts-culture"
  },
  {
    "id": "folk-and-traditional-arts-project-grant",
    "name": "Folk and Traditional Arts Project Grant",
    "funder": "Colorado Creative Industries (OEDIT), with History Colorado and Colorado State Archives; supported by the NEA",
    "awardRange": "$3,000",
    "funds": "$3,000 to create, present, or teach folk/traditional arts, or to document cultural heritage (community archiving, oral histories, photojournalism, video). No match required; can fully fund a project.",
    "fit": "Strong fit for the North Fork's living agricultural, ranching, orchard, winemaking, and coal-mining heritage, and for Indigenous/Hispano traditions. Individual artists, collectives, and nonprofits in Paonia are eligible; fiscal sponsors allowed.",
    "eligibleApplicant": "both",
    "cycle": "Annual (opens late Jan, due mid-Apr)",
    "nextDeadline": "Annual cycle: opens late January, final deadline mid…",
    "communityTheme": "arts-culture",
    "confidence": "medium",
    "link": "https://oedit.colorado.gov/folk-and-traditional-arts-project-grant",
    "category": "arts-culture"
  },
  {
    "id": "nea-grants-for-arts-projects-incl-challe",
    "name": "NEA Grants for Arts Projects (incl. Challenge America)",
    "funder": "National Endowment for the Arts",
    "awardRange": "Challenge America: $10,000 (flat). Grants for Arts Projects: $10,000-$100,000 (subgranting $30,000-$150,000)",
    "funds": "Project grants for arts programming. Challenge America: flat $10,000 for small/first-time/underserved-community applicants. Standard GAP: $10,000-$100,000 (local arts agency subgranting $30,000-$150,000). 1:1 cost-share match required.",
    "fit": "NEA explicitly welcomes first-time applicants and organizations serving rural communities of all sizes, fitting Paonia. Challenge America's flat $10,000 is the most accessible route for a small-town arts nonprofit. Note the org must have 5 years of prior arts programming and $20,000+ annual operating expenses - an established local arts nonprofit, not the Town's first-ever project, is the realistic applicant.",
    "eligibleApplicant": "nonprofit",
    "cycle": "Two cycles annually (Feb and July)",
    "nextDeadline": "Next deadline is the July 2026 cycle",
    "communityTheme": "arts-culture",
    "confidence": "high",
    "link": "https://www.arts.gov/grants/grants-for-arts-projects",
    "category": "arts-culture"
  },
  {
    "id": "advance-colorado-broadband-advance-local",
    "name": "Advance Colorado Broadband - Advance-Local Grant Program",
    "funder": "Colorado Broadband Office (CBO)",
    "awardRange": "Drawn from a ~$27.4M pool across all projects; per-award amounts vary by project type and scope (no fixed cap published).",
    "funds": "~$27.4M from the state High Cost Support Mechanism for middle-mile (Tier I, up to 60% of funds), last-mile, and non-deployment/digital-access projects (Tier II, up to 40%).",
    "fit": "Moderate fit. The program primarily funds internet service providers and local governments deploying infrastructure, which is a heavier lift for a town of 1,500. The more accessible angles for Paonia are the Tier II non-deployment / digital-access track (digital equity, device/skills programs - a fit for a local nonprofit like The Learning Council) and earning 'Broadband Ready' community status to strengthen future applications.",
    "eligibleApplicant": "both",
    "cycle": "Middle-mile cycle now; last-mile and digital-access cycle summer 2026",
    "nextDeadline": "Middle-Mile window open through June 29, 2026",
    "communityTheme": "A rural town closing its connectivity and digital-access gap",
    "confidence": "medium",
    "link": "https://broadband.colorado.gov/advance-colorado-broadband",
    "category": "broadband"
  },
  {
    "id": "colorado-community-revitalization-tax-cr",
    "name": "Colorado Community Revitalization Tax Credit (CRTC)",
    "funder": "Colorado Creative Industries and Business Funding & Incentives (OEDIT)",
    "awardRange": "Tax credit up to $3 million per project, up to 25% of total eligible expenses",
    "funds": "Transferable state tax credit for mixed-use capital improvement projects (construction, rehab, conversion, remodel) that support creative industries and workers - including creative-use performance/exhibition space and live-work/affordable housing for creative workers. Up to $3 million per project, covering up to 25% of eligible expenses.",
    "fit": "Excellent structural fit: projects must sit within a creative district, historic district, neighborhood commercial center, or main street. Paonia is both a Certified Creative District and has a historic Main Street, so a downtown placemaking/rehab project (e.g., the planned co-working/business innovation hub) could qualify. Applicant is a business or nonprofit undertaking the capital project.",
    "eligibleApplicant": "both",
    "cycle": "Annual through tax year 2029 (preliminary app ~Jan-Feb, full app ~Mar-Apr)",
    "nextDeadline": "Annual program through tax year 2029",
    "communityTheme": "downtown",
    "confidence": "high",
    "link": "https://oedit.colorado.gov/programs-and-funding/tax-credits/colorado-community-revitalization-tax-credit",
    "category": "downtown"
  },
  {
    "id": "colorado-main-street-program-community-d",
    "name": "Colorado Main Street Program - Community Designation",
    "funder": "Colorado DOLA - Division of Local Government (Colorado Main Street, a Main Street America Coordinating Program)",
    "awardRange": "Noncompetitive grants and scholarships to designated communities (amounts vary by tier and program year); primary value is technical assistance and the designation itself.",
    "funds": "Technical assistance in the Main Street Approach plus noncompetitive grants and scholarships to selected communities. Partially funded by History Colorado State Historical Fund.",
    "fit": "Excellent fit. Paonia has a historic Main Street and a state-certified Creative District, exactly the downtown-revitalization profile Colorado Main Street supports. Designation also unlocks the Community Revitalization Tax Credit pathway and other downtown resources.",
    "eligibleApplicant": "both",
    "cycle": "Advisory Board reviews in February, April, and September each year",
    "nextDeadline": "The Main Street Advisory Board reviews applications…",
    "communityTheme": "A historic Main Street and certified arts/creative town pursuing downtown revitalization",
    "confidence": "high",
    "link": "https://dlg.colorado.gov/main-street",
    "category": "downtown"
  },
  {
    "id": "community-development-block-grant-public",
    "name": "Community Development Block Grant - Public Facilities (CDBG-PF) Construction",
    "funder": "Colorado DOLA - Division of Local Government (federal HUD CDBG, non-entitlement)",
    "awardRange": "Up to $600,000",
    "funds": "Federal CDBG construction grants for public facilities and infrastructure: acquisition, construction, reconstruction, rehabilitation, or installation of public improvements/facilities. Max award $600,000.",
    "fit": "Strong fit for a non-entitlement rural town. Paonia, as a small disadvantaged community, can use CDBG-PF for public facilities and infrastructure that meet a national objective (e.g. benefit to low- and moderate-income residents).",
    "eligibleApplicant": "town",
    "cycle": "Annual spring application window",
    "nextDeadline": "CDBG-PF Construction application window: March 1 - M…",
    "communityTheme": "A non-entitlement rural town funding public facilities for low- and moderate-income residents",
    "confidence": "high",
    "link": "https://dlg.colorado.gov/community-development-block-grant-cdbg",
    "category": "downtown"
  },
  {
    "id": "coal-transition-community-grants-phase-i",
    "name": "Coal Transition Community Grants (Phase II Community Assistance Grants)",
    "funder": "Colorado Office of Just Transition (CDLE) in partnership with OEDIT",
    "awardRange": "Share of a $9.6 million pool; awards sized to project (community/regional scale)",
    "funds": "$9.6 million in Coal Transition Community Grants supporting regional economic and workforce development that expands local business, creates good-paying jobs, and diversifies coal-affected local economies. Grant-writing assistance (a state-provided grant writer) is available for eligible community entities.",
    "fit": "Strong and distinctive. Delta and Gunnison counties (West Elk Mine, Elk Creek Mine) are a designated Tier Two Coal Transition Community, so Paonia-area entities qualify. Grants are for eligible community entities (taxing districts, local governments, regional partners), not individuals. Good fit for economic-diversification, infrastructure, or workforce projects tied to Paonia's post-coal economy.",
    "eligibleApplicant": "both",
    "cycle": "Rolling (Phase II currently open)",
    "nextDeadline": "Rolling",
    "communityTheme": "Just transition from coal (West Elk Mine)",
    "confidence": "high",
    "link": "https://cdle.colorado.gov/offices/the-office-of-just-transition/programs-for-coal-transition-communities",
    "category": "energy-transition"
  },
  {
    "id": "colorado-circular-communities-c3-impact-",
    "name": "Colorado Circular Communities (C3) - Impact & Mini Grants",
    "funder": "Colorado Circular Communities Enterprise (Colorado Department of Public Health & Environment / CDPHE)",
    "awardRange": "Mini Grants: up to $50,000. Impact Grants: $50,000-$500,000.",
    "funds": "Mini Grants up to $50,000 for small, quickly-completed projects (equipment, supplies). Impact Grants $50,000-$500,000 for projects that build Colorado's circular economy (recycling, reuse, composting, waste diversion, full-lifecycle materials management) over an 18-month-or-less period. Free technical assistance also available.",
    "fit": "Solid fit, broad eligibility. Paonia's farms, food businesses, wineries, the school district, or the Town could fund composting, food-waste diversion, reuse, or recycling infrastructure - well-aligned with the North Fork's organic-agriculture and farm-to-table identity. Businesses and nonprofits are eligible too, widening who in Paonia can apply.",
    "eligibleApplicant": "both",
    "cycle": "Applications always open; Impact Grants reviewed in three windows (Jan-Mar, Apr-Jun, Jul-Sep); Mini Grants reviewed continuously",
    "nextDeadline": "Rolling",
    "communityTheme": "agriculture; environment; downtown/business",
    "confidence": "high",
    "link": "https://coloradocircularcommunities.org/funding-opportunities",
    "category": "environment"
  },
  {
    "id": "restore-colorado-program",
    "name": "RESTORE Colorado Program",
    "funder": "National Fish & Wildlife Foundation (NFWF) with Colorado partners (CPW, CDA, GOCO and others)",
    "awardRange": "Minimum grant $100,000; ~10 awards expected per cycle (no published maximum).",
    "funds": "Voluntary restoration, enhancement, and expansion of high-priority wildlife habitat: watershed resilience (wetlands, riparian, upland/forest), grasslands, sagebrush rangelands, big-game winter range and migration corridors, capacity building, and urban habitat.",
    "fit": "Good fit for a habitat/restoration project led by a nonprofit, district, or the Town. North Fork riparian and big-game/sagebrush habitat work qualifies. Minimum grant $100,000, so best suited to a substantial restoration project, likely partner-led (e.g. Western Slope Conservation Center).",
    "eligibleApplicant": "both",
    "cycle": "Annual RFP, full proposals typically due mid-November",
    "nextDeadline": "2026 RFP cycle is CLOSED - the full-proposal deadlin…",
    "communityTheme": "conservation; outdoor recreation; agriculture-adjacent habitat",
    "confidence": "high",
    "link": "https://www.nfwf.org/programs/restore-colorado-program",
    "category": "environment"
  },
  {
    "id": "southwest-rivers-headwaters-fund",
    "name": "Southwest Rivers Headwaters Fund",
    "funder": "National Fish & Wildlife Foundation (NFWF) with the Bureau of Reclamation and partners",
    "awardRange": "Grant requests generally $100,000 to $600,000.",
    "funds": "Restore, protect, and enhance aquatic and riparian species of conservation concern and their habitats in the headwaters of the Colorado River and Rio Grande watersheds.",
    "fit": "Good fit. Paonia is in the Colorado River headwaters (North Fork of the Gunnison). Aquatic/riparian restoration on the North Fork fits squarely. Best for a substantial project led by a nonprofit, district, or government partner.",
    "eligibleApplicant": "both",
    "cycle": "Annual RFP, full proposals typically due in November",
    "nextDeadline": "2026 RFP cycle is CLOSED - the full-proposal deadlin…",
    "communityTheme": "water/watershed; conservation",
    "confidence": "medium",
    "link": "https://www.nfwf.org/programs/southwest-rivers-headwaters-fund",
    "category": "environment"
  },
  {
    "id": "state-historical-fund-competitive-genera",
    "name": "State Historical Fund - Competitive General Grant",
    "funder": "History Colorado, State Historical Fund",
    "awardRange": "General Grant $50,001-$250,000 (Mini Grant up to $50,000)",
    "funds": "Bricks-and-mortar preservation of designated historic properties, archaeology, and preservation education/training. General Grant: $50,001-$250,000 (Mini Grant up to $50,000 also available).",
    "fit": "Strong for Paonia's historic Main Street. Requires National, State, or Local designation prior to application for physical-work projects (or movement toward designation). The Town, a nonprofit, or a property owner can apply. Grant-writing costs are not reimbursable.",
    "eligibleApplicant": "both",
    "cycle": "Spring and Fall rounds annually; rolling LOIs (due 14+ days before each deadline)",
    "nextDeadline": "Rolling",
    "communityTheme": "Historic Main Street preservation",
    "confidence": "high",
    "link": "https://www.historycolorado.org/competitive-grants",
    "category": "historic-preservation"
  },
  {
    "id": "local-planning-capacity-lpc-grant-progra",
    "name": "Local Planning Capacity (LPC) Grant Program (Proposition 123)",
    "funder": "Colorado DOLA - Division of Local Government",
    "awardRange": "Up to ~$250,000 suggested maximum (larger for multi-jurisdictional); early-adoption incentive up to $45,000 with no match.",
    "funds": "Grants to increase local government planning-department capacity to expedite review, permitting, and zoning of affordable housing and to meet Proposition 123 fast-track requirements. Suggested max award $250,000; 20% local match (50% for comprehensive plan / land use code updates).",
    "fit": "Directly fits a small town that needs planning capacity to enable housing. The early-adoption incentive is especially attractive: up to $45,000 with NO local match for jurisdictions that adopt an expedited (fast-track) development review process for affordable housing by June 30, 2026.",
    "eligibleApplicant": "town",
    "cycle": "Recurring spring and fall cycles",
    "nextDeadline": "Fall 2026 cycle expected in September 2026",
    "communityTheme": "A small rural town building the planning capacity to allow more housing",
    "confidence": "high",
    "link": "https://dlg.colorado.gov/local-planning-capacity-grant-program",
    "category": "housing"
  },
  {
    "id": "proposition-123-affordable-housing-finan",
    "name": "Proposition 123 Affordable Housing Financing Fund (Land Banking, Equity, Concessionary Debt, Modular Finance)",
    "funder": "OEDIT / Colorado Housing and Finance Authority (CHFA), with DOLA Division of Housing",
    "awardRange": "Varies by program; equity and debt deals run into the millions per project. Land Banking awards are smaller acquisition-scale grants/forgivable loans.",
    "funds": "Grants and forgivable loans (Land Banking), equity investment (Equity), and concessionary loans (Concessionary Debt / Modular Finance) for affordable housing. ~$300M+ deployed statewide; ~$340M awarded to date across the fund.",
    "fit": "Supports affordable housing creation and preservation in a small rural town. Land Banking (grants/forgivable loans to acquire and preserve land) is the most accessible entry point for a town or local nonprofit. KEY ELIGIBILITY GATE: a project is only eligible if it sits in a jurisdiction that has filed a Proposition 123 Local Government Affordable Housing Commitment with DOLA's Division of Housing. Paonia must have a current commitment on file to access this fund.",
    "eligibleApplicant": "both",
    "cycle": "Equity on an annual round (Jan-Feb); Land Banking / Concessionary Debt / Modular on rolling NOFAs",
    "nextDeadline": "Rolling",
    "communityTheme": "A rural disadvantaged community needing workforce and affordable housing",
    "confidence": "high",
    "link": "https://coloradoaffordablehousingfinancingfund.com/",
    "category": "housing"
  },
  {
    "id": "fishing-is-fun-grant",
    "name": "Fishing is Fun Grant",
    "funder": "Colorado Parks & Wildlife (federal Sport Fish Restoration funds)",
    "awardRange": "Program awards up to $650,000 statewide annually across projects; 25% minimum match. Per-project caps are not published; contact the coordinator.",
    "funds": "Matching grants for projects that improve angling opportunities: new or improved public angling access, in-stream/lake habitat improvements, and related site and facility development.",
    "fit": "Fits Paonia's North Fork river fishing identity. The Town, or a local angling/conservation nonprofit, could fund an access or habitat improvement on the North Fork of the Gunnison or Paonia River Park frontage.",
    "eligibleApplicant": "both",
    "cycle": "Annual; applications typically open in November and are due in early January",
    "nextDeadline": "The 2026 round closed January 9, 2026",
    "communityTheme": "fishing",
    "confidence": "medium",
    "link": "https://cpw.state.co.us/fishing-fun-grants",
    "category": "parks-trails"
  },
  {
    "id": "goco-community-impact-grant",
    "name": "GOCO Community Impact Grant",
    "funder": "Great Outdoors Colorado (GOCO)",
    "awardRange": "$100,000 - $2,000,000 per project (grants above $2M considered starting FY2027, 1-2 per year)",
    "funds": "Planning and/or construction of new or upgraded parks, trails, natural areas, and other outdoor amenities; stewardship work.",
    "fit": "Paonia's Paonia River Park, trail connections, and West Elk-adjacent outdoor amenities are squarely in scope. The Town can apply directly; a local land trust could partner. Strong fit for a capital parks/trails build.",
    "eligibleApplicant": "town",
    "cycle": "Two cycles per year (summer and winter concept-paper windows)",
    "nextDeadline": "First cycle: concept papers due July 23, 2026; appli…",
    "communityTheme": "outdoor recreation",
    "confidence": "high",
    "link": "https://goco.org/grants/programs/community-impact",
    "category": "parks-trails"
  },
  {
    "id": "land-and-water-conservation-fund-lwcf-st",
    "name": "Land and Water Conservation Fund (LWCF) - State & Local Assistance",
    "funder": "National Park Service, administered in Colorado by Colorado Parks & Wildlife",
    "awardRange": "Not published on the current CPW page; awards are reimbursement grants requiring a 50% non-federal match. Confirm caps with CPW.",
    "funds": "Land acquisition to create new outdoor recreation spaces, or development/redevelopment of existing sites and facilities dedicated to public outdoor recreation (parks, trailheads, river parks).",
    "fit": "Strong fit for acquiring or developing public outdoor recreation land. Recent Colorado awards include river-park acquisitions and park redevelopments in small Western Slope towns (e.g. Pagosa Springs river park, Carbondale park). The Town could fund a Paonia River Park expansion or trailhead.",
    "eligibleApplicant": "town",
    "cycle": "Annual; opens early August, scope/LOI early September, full applications early October",
    "nextDeadline": "Currently closed",
    "communityTheme": "outdoor recreation",
    "confidence": "low",
    "link": "https://cpw.state.co.us/lwcf",
    "category": "parks-trails"
  },
  {
    "id": "non-motorized-trails-grant-state-recreat",
    "name": "Non-Motorized Trails Grant (State Recreational Trails)",
    "funder": "Colorado Parks & Wildlife State Trails Program (funded by GOCO + federal Recreational Trails Program)",
    "awardRange": "Construction & Maintenance: up to $250,000; Planning & Support: up to $45,000; Trails Stewardship (2026 pilot): up to $150,000. 25% match required (10% of that must be cash).",
    "funds": "Trail construction, maintenance, planning, support, and trail stewardship crews on non-motorized trail systems.",
    "fit": "Direct fit for Paonia River Park and West Elk-area trail construction, maintenance, or planning. The Town or a partner nonprofit (e.g. Western Slope Conservation Center) can apply.",
    "eligibleApplicant": "both",
    "cycle": "Annual; posts first business day of August, LOI early September, full applications early October, awards the following spring",
    "nextDeadline": "Next cycle opens August 1, 2026",
    "communityTheme": "outdoor recreation",
    "confidence": "medium",
    "link": "https://cpw.state.co.us/non-motorized-trails-grants",
    "category": "parks-trails"
  },
  {
    "id": "partners-in-the-outdoors-grant",
    "name": "Partners in the Outdoors Grant",
    "funder": "Colorado Parks & Wildlife",
    "awardRange": "Up to $10,000 (no match required, though match is encouraged)",
    "funds": "Small grants for projects and programming that connect people to the outdoors at a local, regional, or statewide scale (programming, events, engagement, stewardship).",
    "fit": "Low-barrier, no-match grant well-sized for a small Paonia nonprofit or the Town to run an outdoor program or event. Good entry point for first-time CPW applicants.",
    "eligibleApplicant": "both",
    "cycle": "Annual; application window June through mid-July",
    "nextDeadline": "Applications open online June 1, 2026 and close July…",
    "communityTheme": "outdoor recreation",
    "confidence": "high",
    "link": "https://cpw.state.co.us/partners-outdoors-grant",
    "category": "parks-trails"
  },
  {
    "id": "goco-pathways-grant-planning-capacity",
    "name": "GOCO Pathways Grant (Planning & Capacity)",
    "funder": "Great Outdoors Colorado (GOCO)",
    "awardRange": "$100,000 to $300,000 per project (no hard maximum; GOCO may revise)",
    "funds": "Planning and capacity-building: research and knowledge-building, data-gathering and analysis, tool/model development, high-level visioning, equity initiatives, climate resilience, community engagement, and expanding staff capacity for outdoor/conservation work.",
    "fit": "Fits a Town- or land-trust-led outdoor recreation master plan, trail/river-corridor visioning, or capacity-building for conservation work, with priority for disproportionately impacted communities (Paonia qualifies as a rural disadvantaged community).",
    "eligibleApplicant": "town",
    "cycle": "Two cycles per year (summer and winter concept-paper windows)",
    "nextDeadline": "First cycle: concept papers due July 23, 2026; appli…",
    "communityTheme": "outdoor recreation planning",
    "confidence": "high",
    "link": "https://goco.org/grants/programs/pathways",
    "category": "planning"
  },
  {
    "id": "usda-community-facilities-direct-loan-gr",
    "name": "USDA Community Facilities Direct Loan & Grant Program",
    "funder": "USDA Rural Development (Colorado state office)",
    "awardRange": "Loans and grants; grant share up to 75% of eligible costs for the smallest, lowest-income communities. No fixed maximum (sized to project and budget).",
    "funds": "Direct loans and grants to purchase, construct, or improve essential community facilities (health care, education, public safety, town buildings, etc.) and buy equipment. Grants graduated by community size/income - up to 75% of eligible project cost for communities of 5,000 or fewer with median household income below the higher of the poverty line or 60% of the state nonmetro median.",
    "fit": "Strong fit. Paonia (pop ~1,500, well under the 20,000 rural threshold, low-income rural area) qualifies for the most favorable grant tier. Works for a wide range of public facility projects. The Town, county, special districts, and local nonprofits are all eligible applicants.",
    "eligibleApplicant": "both",
    "cycle": "Rolling / continuous",
    "nextDeadline": "Rolling",
    "communityTheme": "A small low-income rural town funding essential public facilities",
    "confidence": "high",
    "link": "https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program-12",
    "category": "public-safety"
  },
  {
    "id": "colorado-healthy-rivers-fund",
    "name": "Colorado Healthy Rivers Fund",
    "funder": "CWCB & Water Quality Control Commission, administered by the Colorado Watershed Assembly",
    "awardRange": "Not published on the program page; check the Colorado Watershed Assembly guidelines when the next cycle opens.",
    "funds": "Project Grants (watershed improvement/protection: water quality/quantity monitoring, TMDL implementation, riparian/streambank/habitat restoration, flood protection, channel stability) and Planning Grants (data collection, alternatives analysis, permitting, outreach).",
    "fit": "Strong fit, especially for a watershed nonprofit. Tailored to locally-based, collaborative watershed protection groups - exactly the Western Slope Conservation Center's mission on the North Fork. Funds the kind of river-health and habitat work the North Fork Valley cares about.",
    "eligibleApplicant": "nonprofit",
    "cycle": "Annual, application window typically opens in winter and closes late February",
    "nextDeadline": "Closed for 2026",
    "communityTheme": "water/watershed; conservation",
    "confidence": "medium",
    "link": "https://cwcb.colorado.gov/colorado-healthy-rivers-fund",
    "category": "water"
  },
  {
    "id": "colorado-water-plan-grant-watershed-heal",
    "name": "Colorado Water Plan Grant - Watershed Health & Recreation",
    "funder": "Colorado Water Conservation Board (CWCB), Colorado DNR",
    "awardRange": "Varies by project; $12.5M available in the Watershed Health & Recreation category for the 2026 cycles. No fixed per-grant cap.",
    "funds": "Project funding for planning, design, and implementation of watershed health and recreation projects. For the 2026 cycles, CWCB has ~$40.2M total available across categories, with $12.5M target-allocated to the Watershed Health & Recreation category (set at the May 2026 Board meeting).",
    "fit": "Strong fit. Paonia is a riverfront town on the North Fork of the Gunnison with Paonia River Park and active fishing/boating recreation. The category explicitly funds watershed health plus recreation/river-park work. CWCB's own example projects (e.g. the Shady Island River Park on the Gunnison, and a city/water-district wildfire watershed protection plan) closely mirror what Paonia or the Western Slope Conservation Center could pursue.",
    "eligibleApplicant": "both",
    "cycle": "Two cycles per year, application deadlines July 1 and December 1",
    "nextDeadline": "July 1, 2026",
    "communityTheme": "outdoor recreation; water/watershed; rural disadvantaged community",
    "confidence": "high",
    "link": "https://cwcb.colorado.gov/funding/colorado-water-plan-grants",
    "category": "water"
  },
  {
    "id": "community-funding-partnership",
    "name": "Community Funding Partnership",
    "funder": "Colorado River District (Colorado River Water Conservation District)",
    "awardRange": "Project-scaled; commonly six figures (e.g. $300K grant to the CMU Water Center; $650K+ approved in a single round).",
    "funds": "Funding for multi-purpose Western Slope water projects in five categories: productive agriculture, infrastructure, healthy rivers, watershed health & water quality, and conservation & efficiency. The District has approved well over $650K in single rounds and routinely makes six-figure project grants.",
    "fit": "Excellent fit. Paonia and Delta County are inside the Colorado River District's 15-county Western Slope territory. The District prioritizes exactly Paonia's mix: irrigated agriculture (orchards, vineyards, ditches), healthy rivers, and water infrastructure. The Town, a ditch/irrigation company, a farm, or a nonprofit can apply.",
    "eligibleApplicant": "both",
    "cycle": "Rolling; submit any time. For requests needing Board approval, submit at least six weeks before the next Board meeting.",
    "nextDeadline": "Rolling",
    "communityTheme": "agriculture; water/watershed; conservation",
    "confidence": "high",
    "link": "https://www.coloradoriverdistrict.org/community-funding-partnership/",
    "category": "water"
  },
  {
    "id": "energy-mineral-impact-assistance-fund-gr",
    "name": "Energy/Mineral Impact Assistance Fund Grant (EIAF)",
    "funder": "Colorado Dept. of Local Affairs (DOLA), Division of Local Government",
    "awardRange": "Tier I up to $200,000; Tier II $200,001-$1,000,000",
    "funds": "Infrastructure and asset-building projects (water, wastewater, streets, public facilities, planning) tied to energy and mineral impact in rural Colorado. Tier I up to $200,000; Tier II $200,001 to $1,000,000.",
    "fit": "Strong. Paonia is a former coal region in rural Colorado and the Town and special districts are exactly the eligible entities. The most successful applications show urgency, local commitment, and readiness to start. Ideal for water/wastewater/streets capital projects.",
    "eligibleApplicant": "town",
    "cycle": "Recurring: cycles traditionally close ~April 1, August 1, and December 1 each year",
    "nextDeadline": "Cycle 26-05 closed Feb 13, 2026",
    "communityTheme": "Former coal region / disadvantaged rural community",
    "confidence": "high",
    "link": "https://dlg.colorado.gov/energy-mineral-impact-assistance-fund-grant-eiaf",
    "category": "water"
  },
  {
    "id": "state-revolving-fund-srf-planning-and-de",
    "name": "State Revolving Fund (SRF) Planning and Design & Engineering Grants",
    "funder": "Colorado Dept. of Public Health & Environment (CDPHE), Water Quality Control Division",
    "awardRange": "Planning grants up to $10,000; design/engineering grant amounts vary by project size and need",
    "funds": "Grants to help disadvantaged communities fund the up-front costs of wastewater, stormwater, and drinking water projects. Planning grants up to $10,000 toward a project needs assessment / environmental assessment (20% applicant match). Design & engineering grants reimburse eligible design costs (up to 80% before the SRF loan application, final 20% upon loan execution).",
    "fit": "Strong. Paonia (pop ~1,500) clearly qualifies as a disadvantaged community of 10,000 or fewer. Pairs naturally with an SRF loan for a water or wastewater capital project. Applicant must complete a pre-qualification form and attend a pre-qualification meeting.",
    "eligibleApplicant": "town",
    "cycle": "Recurring RFA windows ~twice per year (subject to EPA allocations), 2026-2028",
    "nextDeadline": "Recurring",
    "communityTheme": "Disadvantaged-community water/wastewater funding",
    "confidence": "medium",
    "link": "https://cdphe.colorado.gov/wq-planning-design-grants",
    "category": "water"
  },
  {
    "id": "water-waste-disposal-loan-grant-program",
    "name": "Water & Waste Disposal Loan & Grant Program",
    "funder": "USDA Rural Development - Water and Environmental Programs (Colorado)",
    "awardRange": "Loans and grants sized to project need; grant portion combined with loan to keep user costs reasonable",
    "funds": "Funding for clean and reliable drinking water systems, sanitary sewage disposal, solid waste disposal, and stormwater drainage in eligible rural areas. Loans, grants, and loan/grant combinations for applicants unable to obtain commercial credit on reasonable terms.",
    "fit": "Strong. Paonia (pop ~1,500) is well under the 10,000-resident rural threshold. The Town or a special district is a textbook applicant for a water or wastewater system project. Preparation can take weeks to months.",
    "eligibleApplicant": "town",
    "cycle": "Year-round / rolling",
    "nextDeadline": "Rolling",
    "communityTheme": "Rural water and wastewater infrastructure",
    "confidence": "high",
    "link": "https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-loan-grant-program-6",
    "category": "water"
  },
  {
    "id": "building-resilient-infrastructure-and-co",
    "name": "Building Resilient Infrastructure and Communities (BRIC)",
    "funder": "FEMA, administered in Colorado by the Division of Homeland Security and Emergency Management (DHSEM)",
    "awardRange": "Up to $50 million federal share per project; smaller capability-building and planning awards also available",
    "funds": "Hazard mitigation projects that reduce risk to life, property, and infrastructure from natural hazards including wildfire, flooding, and drought. Up to $50 million federal share per project; capability/capacity building, project scoping, hazard mitigation planning, and construction. 25% non-federal cost share (lower for some communities).",
    "fit": "Good for wildfire and flood mitigation, which matter in the North Fork Valley. Caveat: FEMA requires a current FEMA-approved Hazard Mitigation Plan covering the jurisdiction by the application deadline; the Town must be covered by Delta County's HMP or join it. Sub-applications go through Colorado DHSEM, not directly to FEMA.",
    "eligibleApplicant": "town",
    "cycle": "Annual competitive (status was disrupted 2025; restored by court order Dec 2025)",
    "nextDeadline": "FEMA published a combined FY2024/FY2025 NOFO",
    "communityTheme": "Wildfire and flood resilience",
    "confidence": "medium",
    "link": "https://mars.colorado.gov/mitigation/bric-and-fma-programs",
    "category": "wildfire"
  },
  {
    "id": "colorado-strategic-wildfire-action-progr",
    "name": "Colorado Strategic Wildfire Action Program (COSWAP) - Workforce Development Grant",
    "funder": "Colorado Dept. of Natural Resources / Colorado State Forest Service",
    "awardRange": "Crew-time awards (value varies); cash grants up to $200,000 (independent corps) or up to $100,000 (training)",
    "funds": "Wildfire mitigation workforce grants: crew-time awards (DOC SWIFT crews and CYCA-accredited conservation corps, paid directly by COSWAP), cash grants for independent conservation corps (up to $200,000), cash grants for project management, and cash grants for wildland-fire/sawyer/prescribed-fire training (up to $100,000). Supports forest thinning, fuelbreaks, chipping, biomass removal, and pile/broadcast burning.",
    "fit": "Good for local fuels-reduction and wildfire-mitigation work. Eligible applicants include local governments, fire protection districts, special districts, and 501(c)(3) nonprofits engaged in fuel reduction or natural-resource management (wildfire councils, watershed/forest collaboratives). North Fork entities have won awards (Hotchkiss Fire District received a 2025 training grant; Delta County received a fuels-mitigation award in 2022). Note: the Strategic Focus Areas list does not include Delta County, so a Paonia project would lean on the statewide training track or an RMRI focal-area tie-in. Confirm geographic eligibility with CSFS.",
    "eligibleApplicant": "both",
    "cycle": "Workforce Development Grant: annual, application window typically fall (Sept-Nov)",
    "nextDeadline": "Annual competitive grant",
    "communityTheme": "Wildfire fuels reduction and mitigation workforce",
    "confidence": "medium",
    "link": "https://dnr.colorado.gov/divisions/forestry/co-strategic-wildfire-action-program",
    "category": "wildfire"
  },
  {
    "id": "colorado-watershed-restoration-grants-wi",
    "name": "Colorado Watershed Restoration Grants (Wildfire Ready Watersheds)",
    "funder": "Colorado Water Conservation Board (CWCB), Colorado DNR",
    "awardRange": "Not published as a fixed range; scaled to project scope.",
    "funds": "Capacity building, planning, engineering, implementation, and post-wildfire emergency funding to reduce susceptibility of values-at-risk to post-wildfire hazards (debris flows, erosion, flooding, fluvial hazards). Includes funding to develop a Wildfire Ready Watersheds Action Plan.",
    "fit": "Strong fit. Paonia sits below forested West Elk watersheds where post-fire debris flow and flooding threaten the town's water supply and the North Fork. The Town, Western Slope Conservation Center, or a local district could pursue a Wildfire Ready Watersheds Action Plan or pre/post-fire stream protection.",
    "eligibleApplicant": "both",
    "cycle": "Rolling, until funds are obligated",
    "nextDeadline": "Rolling",
    "communityTheme": "wildfire; water/watershed; former coal/forest region",
    "confidence": "high",
    "link": "https://cwcb.colorado.gov/watershed-grants",
    "category": "wildfire"
  },
  {
    "id": "forest-restoration-wildfire-risk-mitigat",
    "name": "Forest Restoration & Wildfire Risk Mitigation (FRWRM) Grant",
    "funder": "Colorado State Forest Service (CSU) / Colorado DNR",
    "awardRange": "No fixed per-award min/max; ~$7.04M total in the prior round. Partial awards possible.",
    "funds": "Fuels reduction and forest-health treatments, plus capacity-building, to reduce wildfire risk to communities and watersheds. The 2025-26 round had ~$7.04M available (up to $2M for capacity building).",
    "fit": "Strong fit. Paonia is a forested-interface community in the West Elks with real wildfire exposure to the town and its water supply. The Town, a local fire district, or a nonprofit could fund fuels work or a community wildfire capacity project.",
    "eligibleApplicant": "both",
    "cycle": "Annual RFA, historically opening late summer and closing in fall",
    "nextDeadline": "2025-26 round CLOSED",
    "communityTheme": "wildfire; former coal/forest region; water/watershed",
    "confidence": "medium",
    "link": "https://csfs.colostate.edu/grants/forest-restoration-wildfire-risk-mitigation/",
    "category": "wildfire"
  },
  {
    "id": "equity-in-arts-learning-for-colorado-you",
    "name": "Equity in Arts Learning for Colorado Youth Grant",
    "funder": "Bonfils-Stanton Foundation, Colorado Creative Industries, and Denver Arts & Venues; administered by Think 360 Arts for Learning, with support from the Gates Family Foundation",
    "awardRange": "$10,000 to $25,000",
    "funds": "$10,000-$25,000 for arts-learning projects serving PK-12 youth.",
    "fit": "Fits youth arts education: eligible applicants are Colorado nonprofits or PK-12 schools, with schools required to partner with an artist or arts organization. The Delta County school district in Paonia could partner with the North Fork Valley Creative Coalition or a local teaching artist. Narrower lane (youth/education) than general arts funding.",
    "eligibleApplicant": "both",
    "cycle": "Annual, LOI typically opens ~September",
    "nextDeadline": "The 2026-27 cycle is fully closed",
    "communityTheme": "youth-education",
    "confidence": "low",
    "link": "https://think360arts.org/grant-opportunities/",
    "category": "youth-education"
  },
  {
    "id": "outdoor-equity-grant-program",
    "name": "Outdoor Equity Grant Program",
    "funder": "Colorado Parks & Wildlife (Outdoor Equity Board)",
    "awardRange": "Up to $100,000",
    "funds": "Projects that reduce barriers to the outdoors for traditionally-excluded youth and families: responsible recreation experiences, conservation opportunities, and outdoor job/career training for low-income, racially/ethnically diverse, LGBTQ+, disability-community, and American Indian/Native youth.",
    "fit": "Excellent fit for a Paonia nonprofit like The Learning Council or a youth/school program getting rural North Fork Valley kids outdoors. Paonia's rural low-income profile supports a competitive application.",
    "eligibleApplicant": "both",
    "cycle": "Annual; interest form in spring, full application in late summer",
    "nextDeadline": "Two-step process: Grant Interest Form open April 30…",
    "communityTheme": "youth outdoor access",
    "confidence": "high",
    "link": "https://cpw.state.co.us/outdoor-equity-grant-program",
    "category": "youth-education"
  }
] as Opportunity[];
