// AUTO-GENERATED by scripts/sync-meetings.mjs from the Town's CivicClerk
// portal (paoniaco.portal.civicclerk.com). Do not edit by hand; run
// `npm run sync:meetings` to refresh. Generated 2026-05-31.
//
// Real Town Board meetings (regular, work sessions, specials, training), so
// work sessions and reschedules a date rule would miss are included. CivicClerk
// stores start times as local wall-clock with a bogus Z; the sync reinterprets
// them in America/Denver.

export type MeetingKind =
  | "regular"
  | "work-session"
  | "special"
  | "training"
  | "other";

export interface RawMeeting {
  eventId: number;
  start: string;
  title: string;
  kind: MeetingKind;
  body: string;
  eventUrl: string;
}

const BODY = "Board of Trustees";
const ev = (id: number) => `https://paoniaco.portal.civicclerk.com/event/${id}/files`;

export const RAW_MEETINGS: RawMeeting[] = [
  { eventId: 566, start: "2026-04-14T17:00:00-06:00", title: "04/14/2026 Town Board Work Session", kind: "work-session", body: BODY, eventUrl: ev(566) },
  { eventId: 498, start: "2026-04-14T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(498) },
  { eventId: 511, start: "2026-04-28T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(511) },
  { eventId: 499, start: "2026-05-12T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(499) },
  { eventId: 572, start: "2026-05-22T18:00:00-06:00", title: "5/22/2026 Special Board Meeting", kind: "special", body: BODY, eventUrl: ev(572) },
  { eventId: 512, start: "2026-05-26T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(512) },
  { eventId: 573, start: "2026-05-29T14:30:00-06:00", title: "5/29/2056 Special Board Meeting", kind: "special", body: BODY, eventUrl: ev(573) },
  { eventId: 581, start: "2026-06-02T18:30:00-06:00", title: "Board Agenda Work Session", kind: "work-session", body: BODY, eventUrl: ev(581) },
  { eventId: 500, start: "2026-06-09T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(500) },
  { eventId: 582, start: "2026-06-16T18:30:00-06:00", title: "Board Agenda Work Session", kind: "work-session", body: BODY, eventUrl: ev(582) },
  { eventId: 513, start: "2026-06-23T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(513) },
  { eventId: 501, start: "2026-07-14T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(501) },
  { eventId: 514, start: "2026-07-28T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(514) },
  { eventId: 502, start: "2026-08-11T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(502) },
  { eventId: 515, start: "2026-08-25T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(515) },
  { eventId: 503, start: "2026-09-08T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(503) },
  { eventId: 516, start: "2026-09-22T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(516) },
  { eventId: 504, start: "2026-10-13T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(504) },
  { eventId: 517, start: "2026-10-27T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: BODY, eventUrl: ev(517) },
];
