// AUTO-GENERATED by scripts/sync-meetings.mjs from the Town's CivicClerk
// portal (paoniaco.portal.civicclerk.com). Do not edit by hand; run
// `npm run sync:meetings` to refresh. The daily GitHub Action commits a
// fresh copy whenever the Town's calendar changes (see the commit date).
//
// Every public body the Town posts (Board of Trustees, Planning Commission,
// Tree Board, ad hoc committees, Zoning Board of Adjustments), so work sessions
// and reschedules a date rule would miss are included. CivicClerk stores start
// times as local wall-clock with a bogus Z; the sync reinterprets them in
// America/Denver.

export type MeetingKind =
  | "regular"
  | "work-session"
  | "special"
  | "training"
  | "other";

export type BodyKey =
  | "board"
  | "planning"
  | "tree"
  | "adhoc"
  | "zoning"
  | "other";

export interface RawMeeting {
  eventId: number;
  start: string;
  title: string;
  kind: MeetingKind;
  body: string;
  bodyKey: BodyKey;
  eventUrl: string;
}

const ev = (id: number) => `https://paoniaco.portal.civicclerk.com/event/${id}/files`;

export const RAW_MEETINGS: RawMeeting[] = [
  { eventId: 570, start: "2026-06-15T18:00:00-06:00", title: "Zoning Board of Adjustments & Appeals", kind: "other", body: "Zoning Board of Adjustments", bodyKey: "zoning", eventUrl: ev(570) },
  { eventId: 575, start: "2026-06-16T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(575) },
  { eventId: 593, start: "2026-06-16T18:30:00-06:00", title: "Special Town Board Meeting", kind: "special", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(593) },
  { eventId: 592, start: "2026-06-16T18:45:00-06:00", title: "Board Water Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(592) },
  { eventId: 594, start: "2026-06-18T13:00:00-06:00", title: "6/18/2026 Trustee's Town Facilities Tour", kind: "other", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(594) },
  { eventId: 596, start: "2026-06-22T18:30:00-06:00", title: "Zoning Board of Adjustments & Appeals", kind: "other", body: "Zoning Board of Adjustments", bodyKey: "zoning", eventUrl: ev(596) },
  { eventId: 513, start: "2026-06-23T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(513) },
  { eventId: 585, start: "2026-07-07T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(585) },
  { eventId: 584, start: "2026-07-07T18:30:00-06:00", title: "Town Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(584) },
  { eventId: 527, start: "2026-07-13T18:00:00-06:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(527) },
  { eventId: 501, start: "2026-07-14T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(501) },
  { eventId: 597, start: "2026-07-21T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(597) },
  { eventId: 595, start: "2026-07-21T18:30:00-06:00", title: "Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(595) },
  { eventId: 514, start: "2026-07-28T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(514) },
  { eventId: 528, start: "2026-08-03T18:00:00-06:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(528) },
  { eventId: 1632, start: "2026-08-04T09:30:00-06:00", title: "Board Tour of the Springs", kind: "other", body: "Public Meeting", bodyKey: "other", eventUrl: ev(1632) },
  { eventId: 576, start: "2026-08-04T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(576) },
  { eventId: 1605, start: "2026-08-04T18:30:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1605) },
  { eventId: 1631, start: "2026-08-11T18:30:00-06:00", title: "08/11/2026 Regular Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1631) },
  { eventId: 1600, start: "2026-08-18T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(1600) },
  { eventId: 1634, start: "2026-08-18T18:30:00-06:00", title: "Special Town Board Meeting", kind: "special", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1634) },
  { eventId: 1618, start: "2026-08-18T18:45:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1618) },
  { eventId: 515, start: "2026-08-25T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(515) },
  { eventId: 577, start: "2026-09-01T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(577) },
  { eventId: 587, start: "2026-09-01T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(587) },
  { eventId: 1606, start: "2026-09-01T18:30:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1606) },
  { eventId: 529, start: "2026-09-07T18:00:00-06:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(529) },
  { eventId: 503, start: "2026-09-08T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(503) },
  { eventId: 1601, start: "2026-09-15T17:15:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(1601) },
  { eventId: 1619, start: "2026-09-15T18:30:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1619) },
  { eventId: 516, start: "2026-09-22T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(516) },
  { eventId: 530, start: "2026-10-05T18:00:00-06:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(530) },
  { eventId: 578, start: "2026-10-06T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(578) },
  { eventId: 588, start: "2026-10-06T17:00:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(588) },
  { eventId: 1607, start: "2026-10-06T18:30:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1607) },
  { eventId: 504, start: "2026-10-13T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(504) },
  { eventId: 1602, start: "2026-10-20T17:15:00-06:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(1602) },
  { eventId: 1620, start: "2026-10-20T18:30:00-06:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1620) },
  { eventId: 517, start: "2026-10-27T18:30:00-06:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(517) },
  { eventId: 531, start: "2026-11-02T18:00:00-07:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(531) },
  { eventId: 579, start: "2026-11-03T17:00:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(579) },
  { eventId: 589, start: "2026-11-03T17:00:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(589) },
  { eventId: 1608, start: "2026-11-03T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1608) },
  { eventId: 505, start: "2026-11-10T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(505) },
  { eventId: 544, start: "2026-11-17T17:15:00-07:00", title: "Tree Board", kind: "other", body: "Tree Board", bodyKey: "tree", eventUrl: ev(544) },
  { eventId: 1603, start: "2026-11-17T17:15:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(1603) },
  { eventId: 1621, start: "2026-11-17T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1621) },
  { eventId: 518, start: "2026-11-24T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(518) },
  { eventId: 580, start: "2026-12-01T17:00:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(580) },
  { eventId: 590, start: "2026-12-01T17:00:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(590) },
  { eventId: 1609, start: "2026-12-01T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1609) },
  { eventId: 532, start: "2026-12-07T18:00:00-07:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(532) },
  { eventId: 506, start: "2026-12-08T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(506) },
  { eventId: 545, start: "2026-12-15T17:15:00-07:00", title: "Tree Board", kind: "other", body: "Tree Board", bodyKey: "tree", eventUrl: ev(545) },
  { eventId: 1604, start: "2026-12-15T17:15:00-07:00", title: "Ad Hoc Short-Term Rental Committee", kind: "other", body: "Ad Hoc Committee", bodyKey: "adhoc", eventUrl: ev(1604) },
  { eventId: 1622, start: "2026-12-15T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1622) },
  { eventId: 519, start: "2026-12-22T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(519) },
  { eventId: 533, start: "2027-01-04T18:00:00-07:00", title: "Planning Commission", kind: "other", body: "Planning Commission", bodyKey: "planning", eventUrl: ev(533) },
  { eventId: 1610, start: "2027-01-05T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1610) },
  { eventId: 507, start: "2027-01-12T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(507) },
  { eventId: 546, start: "2027-01-19T17:15:00-07:00", title: "Tree Board", kind: "other", body: "Tree Board", bodyKey: "tree", eventUrl: ev(546) },
  { eventId: 1623, start: "2027-01-19T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1623) },
  { eventId: 520, start: "2027-01-26T18:30:00-07:00", title: "Regular Town Board Meeting", kind: "regular", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(520) },
  { eventId: 1611, start: "2027-02-02T18:30:00-07:00", title: "Standing Board Work Session", kind: "work-session", body: "Board of Trustees", bodyKey: "board", eventUrl: ev(1611) },
];
